### PR TITLE
Fail gracefully

### LINKED ISSUE #103: Make cache optional
I think the cache should be optional in case we face some issues with it. To that end, get_gen() should gain an argument `cache` that would be true by default.

### LINKED ISSUE #106: use httr2
The rmangal package currently relies on the httr package for all HTTP requests (GET, POST, PUT, DELETE). Since httr is in maintenance mode and httr2 is its successor, we should migrate all network operations to httr2 to ensure long-term stability and support.

### LINKED ISSUE #113: Issue accessing all networks using "get_collection"
Hi there,

I am trying to use rmangal to do some network analysis of your full dataset of networks. I apologize if there is a simple solution, but for some reason, I encounter these errors when scaling up the "get_collection" function from a few networks to all of the networks in your dataset.

For example:

search_networks("", verbose = F) %>% get_collection()
Error in names(mg_network$interactions) <- `*vtmp*` :                                                                               
  attempt to set an attribute on NULL

I also tried getting the collection by network ID. If you get collections by a smaller subset of network ID, it works. 
all_networks <- search_networks("", verbose = F) # 1487 networks
get_collection(c(all_networks$id[1000:1300]), verbose = F) %>% combine_mgNetworks()

But if you try using all network IDs, you run into the same error above.
get_collection(c(all_networks$id[1:1487]), verbose = F) %>% combine_mgNetworks()
Error in names(mg_network$interactions) <- `*vtmp*` :                                                                               
  attempt to set an attribute on NULL

I would appreciate any help or thoughts on accessing the full dataset in Mangal. Thank you very much for your help!

### PR DESCRIPTION
**Pull request by KevCaz**
The main goal of the PR was to fail gracefully. While working on this, I switch the core from `httr` to  `httr2` (which resolves #106). 
Note that all previous tests passed, a few new tests have been added. 

This PR:
- fixes #113 
- resolves #106 
- resolves #103

### CODE REVIEW

File: R/client_core.R [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+
+
+rmangal_request_singleton <- function(endpoint = "", id, ...) {
+  stopifnot(length(id) == 1)
+  req <- rmangal_api_url() |>
+    httr2::req_url_path_append(rmangal_endpoint_path(endpoint)) |>
+    httr2::req_url_path_append(id) |>
+    httr2::req_user_agent("rmangal") |>
+    httr2::req_headers("Content-type" = "application/json") |>
+    # httr2::req_cache(tempdir()) |>
```
Comment (BenMerSci) [inline R/client_core.R]: Should we remove unused code?

File: R/client_core.R [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+#'
+#' @noRd
+
+rmangal_api_url <- function(base = "https://mangal.io/api", version = "v2") {
+  paste(base, version, sep = "/") |>
+    httr2::request()
+}
+
+
+rmangal_request <- function(endpoint = "", query = NULL, limit = 100, ...) {
```
Comment (BenMerSci) [inline R/client_core.R]: Shouldn't the parameter `endpoint` have no default value (just by principle), since it has to have a value to work? (Eventhough it'll always have a value since `rmangal_request` is always used within another function which declares the target endpoint). Or is there something I'm missing and it needs to have an empty string as default value?

File: R/zzz.R [hunk 3]
```diff
@@ -130,238 +109,83 @@ switch_sf <- function(x) {
...
-    if (httr::http_error(resp)) {
-      if (verbose) msg_request_fail(resp)
-      errors <- append(errors, ids[i])
-    } else {
-      # coerce body to output desired
-      responses$body[[i]] <- resp_raw(resp)
-      responses$response[[i]] <- resp
-    }
+# message
+rmangal_inform <- function(..., .envir = parent.frame()) {
```
Comment (BenMerSci) [inline R/zzz.R]: Should we document more (in the README or elsewhere) for the user that verbose option is now defined package-wise instead of function-wise, or it's obvious?

File: R/client_core.R (hunk 1 above)
Comment (KevCaz) [reply R/client_core.R]: I will add the cache, I thought I had that done already, but I guess I did not push this piece yet.

File: R/client_core.R (hunk 2 above)
Comment (KevCaz) [reply R/client_core.R]: Good point! No good reason to have the empty string here.

File: R/zzz.R (hunk 3 above)
Comment (KevCaz) [reply R/zzz.R]: Yes, that's something that needs to be added somewhere!

File: R/client_core.R (hunk 2 above)
Comment (KevCaz) [reply R/client_core.R]: See [6e64a3a](https://github.com/ropensci/rmangal/pull/117/commits/6e64a3a127104f084b197f5bc295844765d6dd9d)

File: R/zzz.R (hunk 3 above)
Comment (BenMerSci) [reply R/zzz.R]: In the README? In a vignette? Is there a more appropriate option?

Comment (KevCaz) [reply R/zzz.R]: I mention it in the README, but that's not enough, I think it should be added in the vignette.

**Comment by BenMerSci** [comment]
@KevCaz Do we know what exactly was failing ungracefully #115 (to be sure its fixed)? (The link in the issue is broken)

**Comment by KevCaz** [comment]
> @KevCaz Do we know what exactly was failing ungracefully #115 (to be sure its fixed)? (The link in the issue is broken)

@BenMerSci, all I know is what's in #117 , checks seem fine https://cran-archive.r-project.org/web/checks/2024/2024-03-01_check_results_rmangal.html. Let's double-check that we are failing gracefully properly 😄 .

https://forum.posit.co/t/internet-resources-should-fail-gracefully/49199/12
